### ISSUE TITLE
downsample module has been moved to the theano.tensor.signal.pool module.   "downsample module has been moved to the theano.tensor.signal.pool module.")

### ISSUE THREAD

**Issue by JustVugg** [llSourcell/AI_Writer#1]
`/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Traceback (most recent call last):
  File "/Users/vincenzofornaro/PycharmProjects/machine/run.py", line 1, in <module>
    import generate
  File "/Users/vincenzofornaro/PycharmProjects/machine/generate.py", line 14, in <module>
    import config
  File "/Users/vincenzofornaro/PycharmProjects/machine/config.py", line 21, in <module>
    if not config.FLAG_CPU_MODE:
AttributeError: 'module' object has no attribute 'FLAG_CPU_MODE'`

I have this error when I start the .py

**Comment by psychomonkey911** [comment]
Traceback (most recent call last):
when i start .py i have this error
```
  File "start.py", line 2, in <module>
    z = generate.load_all()
  File "/home/sky/AI_Writer/generate.py", line 82, in load_all
    print config.paths['decmodel']
AttributeError: 'module' object has no attribute 'paths'
```

**Comment by vibhanshu2014** [comment]
I am getting same error

print config.paths['decmodel']
AttributeError: 'module' object has no attribute 'paths'

Anybody please help me in resolving the same

**Comment by shivaraj-bh** [comment]
https://github.com/llSourcell/AI_Writer/issues/5  Check here for a solution
